apiVersion: v1
kind: Secret

metadata:
  name: renter-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds


stringData:
  type: git
  url: https://github.com/aryalsaurav
  githubAppID: "123456"
  githubAppInstallationID: "123456"
  githubAppPrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----
